// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1c_v2B1UbTBd0vec5owbp_Bcbc6YU5Pw',
    appId: '1:922134582445:web:b06cb6b05ec8a219696224',
    messagingSenderId: '922134582445',
    projectId: 'fir-task-9f6bc',
    authDomain: 'fir-task-9f6bc.firebaseapp.com',
    storageBucket: 'fir-task-9f6bc.appspot.com',
    measurementId: 'G-53FK2ZC0H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkZ-BVBDOhDxFlfnEhhKUF_ACmjjEfkbo',
    appId: '1:922134582445:android:92f1eab5d93f22c7696224',
    messagingSenderId: '922134582445',
    projectId: 'fir-task-9f6bc',
    storageBucket: 'fir-task-9f6bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqSaMVNM7AGTJaOQC2E1HpvftwR52qrk',
    appId: '1:922134582445:ios:5686655e2122f7c7696224',
    messagingSenderId: '922134582445',
    projectId: 'fir-task-9f6bc',
    storageBucket: 'fir-task-9f6bc.appspot.com',
    iosBundleId: 'com.example.firebaseTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqSaMVNM7AGTJaOQC2E1HpvftwR52qrk',
    appId: '1:922134582445:ios:5686655e2122f7c7696224',
    messagingSenderId: '922134582445',
    projectId: 'fir-task-9f6bc',
    storageBucket: 'fir-task-9f6bc.appspot.com',
    iosBundleId: 'com.example.firebaseTasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1c_v2B1UbTBd0vec5owbp_Bcbc6YU5Pw',
    appId: '1:922134582445:web:3ebd262a42c91187696224',
    messagingSenderId: '922134582445',
    projectId: 'fir-task-9f6bc',
    authDomain: 'fir-task-9f6bc.firebaseapp.com',
    storageBucket: 'fir-task-9f6bc.appspot.com',
    measurementId: 'G-MGPT511YG8',
  );

}